### ISSUE TITLE
Download Help

### ISSUE THREAD

**Issue by RRRandom-Youtube** [farshadz1997/Microsoft-Rewards-bot-GUI-V2#21]
I downloaded and extracted the file, then I ran the command pip install -r requirements.txt but it didn’t work. Also, installing the driver was very difficult. I put it where you said but it still didn’t work. Please make it easier to use. I wasted many hours trying to make this work.

**Comment by subterfuse** [comment]
This is for windows 10 because I am using it.

So for the chrome driver, you should be able to check which version you have by clicking the triple dots on the top right, and then you would hover over the help to show another popup, then you would click about google chrome.
It should bring you to the page that shows which chrome driver you have by looking at the first three numbers, either 109, 110, or 111. 
Then you go to the chrome driver link in the description of the GitHub and download the driver. It will show you a list of different operating systems, I expect you to know which operating system you have. So when you download it, it will be in a zip file. If you don't have a zip file program like 7zip or WinRAR, you will need one.
Then, you should be left with 2 files, the license, and the one named "chromedriver.exe", we only care about the exe file. now put the file in the C:\Windows folder. You might have a different letter but the default name for the drive will be "C".

The driver should be in the right place if you followed all the steps.

Now on how to install the requirements.txt

You start by opening a cmd prompt, if you do not know how to do this, on windows 10, you hit the windows key on the keyboard or click the windows icon on the bottom left if you have not changed your taskbar location. Then you type "command", it should show you a program called "command prompt". Click it.
Now, this is where you will change the directory to the exact file location where you saved the ms rewards farmer folder.
To do this, you will open up the folder wherever you extracted it, and on windows 10, you click anywhere on the right of the name of the folder like in the screenshot I shared 
![image](https://user-images.githubusercontent.com/75055369/222940840-7db57faa-8559-48e7-a664-89c5cdc99e49.png)

Now copy the text, and head back to the command prompt. and type "cd" and then a space, then paste your copied text with ctrl + v on your keyboard. it should look like my example but without the capital letters "cd FILE DIRECTORY HERE". Now you hit enter on your keyboard. What it did was change the command prompt location to your ms rewards folder.
Lastly copy and paste "pip install -r requirements.txt" and hit enter on your keyboard. It should install all the requirements. 

The program "main.pyw" should run if you have followed all the steps. If not, then I cannot help you if you can't follow the steps.

**Comment by pearlheartgtr** [comment]
To make it easier with Command Prompt, google "add command prompt to right click menu". There are batch files you can run and have it there so all you need to do is open the folder and right click "Command Prompt" and it'll open a terminal in the path of the folder. I have it set up so it runs as administrator.

Here's the one that I use:
[](https://winaero.com/command-prompt-administrator-context-menu/)

**Comment by jvande87** [comment]
Hours? lol lol Stay on Youtube where you belong. This is not for you. 
You should have had this set up and running within 5 minutes.
